### ISSUE TITLE
Support using env vars

### ISSUE THREAD

**Issue by MRayermannMSFT** [Yihcheng/Project2020#2]
I don't want to check in things like usernames and passwords into source. I'd rather be able to set those as environment variables, which can be done with most CI platforms securely. Then, the json config for my test could read those values.

**Comment by Yihcheng** [comment]
Key in OCRProvider of EngineConfig.json is ready for environment variable.
ActionArgument in Steps of TestE2E json file is ready for environment variable.
It's in v.1.1.1 branch now.
