### ISSUE TITLE
Create post-OCR screenshots, or edit the ones you initially take

### ISSUE THREAD

**Issue by MRayermannMSFT** [yihcheng/Project2020#6]
Add the bounding boxes that the OCR results give to the screenshots sent to the OCR service. That way if a test fails, it is easy for me to see what the OCR thought it saw

**Comment by bruceyclee** [comment]
If OCR result can be processed successfully, I'll put red color rectangle to address the location. It's easier for you to review the test steps.

If I can't find a target in OCR result, I'll put target value on the failed screenshot. It helps you quickly know what I am looking for.

**Comment by yihcheng** [comment]
When text is found, the saved image will become 
![image](https://user-images.githubusercontent.com/18693681/47059448-43e58580-d17e-11e8-90aa-0272311a2c40.png)

When text is not found, a message will be displayed in the middle of the image
![image](https://user-images.githubusercontent.com/18693681/47059479-637cae00-d17e-11e8-8d5e-26622954795b.png)

**Comment by yihcheng** [comment]
check-in v.1.1.2 branch directly.

**Comment by MRayermannMSFT** [comment]
Wow! Nice!

**Comment by yihcheng** [comment]
I just did this for "text". I forgot to do the same thing for image. I'll create a new issue to track this.
Also, thanks for this feedback. It's a great feedback for troubleshooting.
