### ISSUE TITLE
Syntax for running a single test is not intuitive

### ISSUE THREAD

**Issue by MRayermannMSFT** [yihcheng/Project2020#7]
I tried doing `./Engine.exe ./E2Efiles/test.json`. It did not work. That is not intuitive. My test file shouldn't need to be in the E2Efiles folder.

**Comment by yihcheng** [comment]
in v.1.1.2 , it becomes
>Engine.exe       -- it will display no input file and usage
>Engine.exe .\path\test.json    -- you can input your test step files here. Multiple files are accepted, separator is "blank space" between files.
